# Generated by Django 5.2.17 on 2026-10-02 13:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tracker.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Receipts are emailed here.', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('other_contact', models.CharField(blank=True, help_text='Messenger, Facebook link, school, etc.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('predicted_intent', models.CharField(blank=True, max_length=40)),
                ('confidence', models.FloatField(default=0)),
                ('reviewed', models.BooleanField(default=False, help_text='Tick once added to intents.json')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('in_development', 'In development'), ('ready_for_pre_oral', 'Ready for pre-oral'), ('ready_for_final', 'Ready for final'), ('fully_paid', 'Fully paid')], db_index=True, default='in_development', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Private. Never shown on the Showcase.')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Only the Showcase fields below become public. Client, price, payments and notes always stay private.', verbose_name='show on Showcase')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='One line under the name.', max_length=160)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated, e.g. Django, MySQL, Bootstrap', max_length=300)),
                ('objectives', models.TextField(blank=True, help_text='One objective per line.')),
                ('purpose', models.TextField(blank=True)),
                ('preview_style', models.CharField(choices=[('crystal', 'Crystal'), ('knot', 'Knot'), ('stack', 'Stacked layers'), ('orbit', 'Orbit'), ('lattice', 'Lattice'), ('prism', 'Prism')], default='crystal', max_length=12, verbose_name='3D preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tracker.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='e.g. GCash reference number', max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tracker.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(help_text='Email, phone or messaging handle', max_length=200)),
                ('system_idea', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('deadline', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('dropped', 'Dropped')], db_index=True, default='new', max_length=12)),
                ('source', models.CharField(choices=[('chatbot', 'Portfolio Assistant'), ('manual', 'Added by hand')], default='manual', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tracker.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%Y/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='tracker.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('quotation', 'Quotation')], default='receipt', max_length=12)),
                ('receipt_number', models.CharField(max_length=24, unique=True)),
                ('public_token', models.CharField(default=tracker.models.new_public_token, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=150)),
                ('system_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], max_length=20)),
                ('payment_date', models.DateField()),
                ('salt', models.CharField(default=tracker.models.new_salt, max_length=32)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('pdf', models.FileField(blank=True, storage=tracker.models.private_storage, upload_to='receipts/%Y/')),
                ('ledger_status', models.CharField(choices=[('unanchored', 'Not on the ledger yet'), ('pending', 'Waiting to be mined'), ('confirmed', 'Confirmed in a block')], default='unanchored', max_length=12)),
                ('tx_id', models.CharField(blank=True, max_length=64, verbose_name='transaction id')),
                ('signed_tx', models.JSONField(blank=True, editable=False, null=True)),
                ('block_index', models.PositiveIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=64)),
                ('emailed_to', models.EmailField(blank=True, max_length=254)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='tracker.payment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
