# Generated by Django 5.2.17 on 2026-10-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'inquiry', 'verbose_name_plural': 'inquiries'},
        ),
    ]
