# Generated by Django 5.2.17 on 2026-10-04 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Message form'), ('chatbot', 'Portfolio Assistant'), ('manual', 'Added by hand')], default='manual', max_length=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Replied'), ('converted', 'Became a project'), ('dropped', 'Closed')], db_index=True, default='new', max_length=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='system_idea',
            field=models.TextField(help_text='What they need, in their own words', verbose_name='message'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=1000)),
                ('display_name', models.CharField(blank=True, help_text='Shown with the review. Left empty, the review says "Verified client".', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Published'), ('hidden', 'Hidden')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tracker.project')),
                ('receipt', models.ForeignKey(blank=True, help_text='The receipt link the client used to write it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.receipt')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
