# Generated by Django 5.2.17 on 2026-10-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_messages_and_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional', max_length=1000),
        ),
    ]
